### ISSUE TITLE
Make output consistent for every command

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/github#12]
- [x] Standard - ideally human friendly, but optimised for being terminal friendly e.g. output can be piped into `awk` or `xargs` and easily consumed with minimal manipulation
- [x] JSON - structured and machine readable

**Comment by sjparkinson** [comment]
> JSON

Nice and easy, we can lean on the responses from Octokit/GitHub's API. Also comes with some great documentation e.g. https://developer.github.com/v3/repos/#response-3.

> Standard / human friendly / terminal friendly?

Human friendly may not always be compatible with being terminal friendly, so we should consider that.

We should do some research into what makes for good, helpful output to the terminal. Are tabs better than spaces when you're working with tools like `awk` for example? There's probably some POSIX standards we could refer to.
