### ISSUE TITLE
Running this tool regularly with `npx` is slow

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/github#25]
#### What's the problem?

Our currently recommended usage of the `@financial-times/github` package is to run it with `npx` e.g.

```
npx @financial-times/github
```

This works great during development, or if the CLI tool is one that you only run very occasionally, however if it's a CLI tool that you run regularly (like this one), it can really slow down your workflow and become quite frustrating to use that tool. This is due to the fact that when `npx` runs a package from the npm registry or from GitHub, it pulls down that package's dependencies _every time_ that you run it - `npx` cleans up all downloaded dependencies after every run of a package. This is an intentional behaviour on the part of `npx`, but it is ultimately what introduces the slowness a developer will experience when running a CLI tool regularly in this way.

### Potential solutions

- Change the recommended usage to installing this tool globally with `npm` (i.e. `npm install -g @financial-times/github`) and integrate a mechanism to notify users when an update is available
- This is the best (and only) idea I have right now - suggestions very welcome!

#### Prior art for package update notifications

Like many developers working with Node.js, I have the [`npm` CLI](https://github.com/npm/cli) globally installed - I think does a pretty nice job of notifying you when there is an update available to install:

![image](https://user-images.githubusercontent.com/2773428/54029827-b7c21200-41a1-11e9-8663-dc53123be988.png)

[See the code that makes the magic happen](https://github.com/npm/cli/blob/86f5bdb91f7a5971953a5171d32d6eeda6a2e972/bin/npm-cli.js#L83-L128)

As you'll see from the code in the `npm` CLI, they're using [update-notifier](https://www.npmjs.com/package/update-notifier). I think it would be worth considering this library as a way for us to introduce update notifications into this package (`@financial-times/github`).

**Comment by taktran** [comment]
I really like this idea! 👍 

I generally have the ebi code checked out and run from `./bin/ebi.js` because of the startup time of `npx`.

`npx` is super great for people new to the repo or reviewing PRs on arbitrary branches, so people don't have to check out the code though, so I think it's still worth mentioning it somewhere in READMEs etc.

**Comment by adambraimbridge** [comment]
Note to self:,  `update-notifier` could possibly be a valuable feature for `secret-squirrel`

**Comment by simonplend** [comment]
To run a global installation of this package, but fallback to downloading it and running it from `npm` if it's not available, we can use the following command:

```
npx @financial-times/github
```

Non-fallback way of running a global installation of this package:

```
github
```

**Comment by simonplend** [comment]
I really like how `npm`'s update notification includes a link to the release notes on GitHub, but I've avoided implementing that in this tool for now as it would require putting together a custom notification and adding another third-party dependency so that this notification can have nice colours. The default notification provided by `update-notifier` seems good for now.
