### ISSUE TITLE
Add support for Pull Requests

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/github#27]
Usage as follows...

```
GitHub Pull Requests

If <body> is "-" read from stdin.

For cross-repository pull requests in the same network, namespace <head> with a user e.g. "username:branch".

Usage:
  github pulls:create [--base <base>] <repo> <head> <title> [<body>]
  github pulls:create-comment <repo> <pull-request> <body>
  github pulls:close <repo> <pull-request>
  github pulls:merge <repo> <pull-request>
  github pulls:request-review <repo> <pull-request> (--team <team>...|--user <user>...)

Arguments:
  <repo>  sjparkinson/example
  <head>  tree-ish
  <pull-request> The number of the pull request.

Options:
  --base <base>             The name of the branch where your changes are implemented.
```

```shell
$ github pulls:create octocat/Hello-World your-branch-here "Initial pull request" <<EOF
This is my initial pull request.
EOF

https://github.com/octocat/Hello-World/pulls/1

$ github pulls:create-comment octocat/Hello-World 1 <<EOF
🚨 DO NOT MERGE!!!
EOF

https://github.com/octocat/Hello-World/pulls/1

$ github pulls:create octocat/Hello-World \
  --base staging-branch \
  "Fix the first pull request" \
  your-bug-fix-branch-here \
  "Woops!"
https://github.com/octocat/Hello-World/pulls/2

$ github pulls:close octocat/Hello-World 1
https://github.com/octocat/Hello-World/pulls/1

$ github pulls:merge octocat/Hello-World 2
https://github.com/octocat/Hello-World/pulls/2

$ github pulls:request-review octocat/Hello-World 2 --user octocat sjparkinson
https://github.com/octocat/Hello-World/pulls/2
```

See https://developer.github.com/v3/pulls/ and https://octokit.github.io/rest.js/#api-Pulls.

**Comment by sjparkinson** [comment]
As an engineer, I would like to open pull request from the command line, so that I can automate creating many pull requests.

As an engineer, I would like to close pull request from the command line, so that I can fix any mistakes I may have made when automating opening hundreds of pull requests.

As an engineer, I would like to add a comment to a pull requests from the command line, so that I can add relevant information that may be helpful to getting a pull requests looked at and merged.

As an engineer, I would like to merge pull requests from the command line, so that I can automatically merge many pull requests in bulk.

As an engineer, I would like to assign a reviewer to a pull request, so that I can make sure somebody reviews the changes I've made.

**Comment by adambraimbridge** [comment]
From the command line:
- [ ] open pull requests
- [ ] close pull requests
- [ ] add a comment to a pull request
- [ ] merge pull requests
- [ ] assign a reviewer to a pull request

**Comment by adambraimbridge** [comment]
![image](https://user-images.githubusercontent.com/224547/55555346-fbdefe80-56dc-11e9-9305-a7efc27c5e7f.png)

![image](https://user-images.githubusercontent.com/224547/55555363-01d4df80-56dd-11e9-9ce0-52a23b53e937.png)

![image](https://user-images.githubusercontent.com/224547/55555374-0b5e4780-56dd-11e9-881e-5bfe0d383298.png)
